language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

env:
  - SYMFONY_VERSION=2.2.*
  - SYMFONY_VERSION=2.3.*
  - SYMFONY_VERSION=dev-master

before_script:
  - composer require symfony/symfony:${SYMFONY_VERSION}

script: phpunit --coverage-text

notifications:
  email: "contact@uniquelibs.com"

matrix:
  allow_failures:
    - env: SYMFONY_VERSION=dev-master